image: crowdar/lippia:3.2.1.1

services:
  - crowdar/lippia:3.2.1.1

before_script:
    - |   # collapsed multi-line command
          echo "Valores de las variables"
          echo "TAG= $TAG"
          echo "TESTTYPE= $TESTTYPE"
          echo "LANG= $LANG"
          echo "CI_COMMIT_MESSAGE= $CI_COMMIT_MESSAGE"

stages:
  - Test

Testing:
  stage: Test
     
  script:
    - | 
      echo "Realizando Pruebas"
      mvn test -P$TESTTYPE -Dcrowdar.cucumber.filter="'$TAG'" -Dcrowdar.cucumber.filter.language="'$LANG'"

  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "main"'
      variables:
        TAG: "@Success"
        TESTTYPE: "Secuencial"
        LANG: "@EN"
    - if: '$CI_COMMIT_BRANCH != "master" && $CI_COMMIT_BRANCH != "main"'
      when: manual

  artifacts:
    when: always
    paths:
      - target/reports/
